Fixed Pmem build tags

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,4 +1,38 @@
 #!/usr/bin/env bash
+#
+# Run all etcd tests
+# ./test
+# ./test -v
+#
+#
+# Run specified test pass
+#
+# $ PASSES=unit ./test
+# $ PASSES=integration ./test
+#
+#
+# Run tests for one package
+# Each pass has different default timeout, if you just run tests in one package or 1 test case then you can set TIMEOUT
+# flag for different expectation
+#
+# $ PASSES=unit PKG=./wal TIMEOUT=1m ./test
+# $ PASSES=integration PKG=client/integration TIMEOUT=1m ./test
+#
+#
+# Run specified unit tests in one package
+# To run all the tests with prefix of "TestNew", set "TESTCASE=TestNew ";
+# to run only "TestNew", set "TESTCASE="\bTestNew\b""
+#
+# $ PASSES=unit PKG=./wal TESTCASE=TestNew TIMEOUT=1m ./test
+# $ PASSES=unit PKG=./wal PMEM=True TESTCASE=TestNew TIMEOUT=1m ./test
+# $ PASSES=unit PKG=./wal TESTCASE="\bTestNew\b" TIMEOUT=1m ./test
+# $ PASSES=integration PKG=client/integration TESTCASE="\bTestV2NoRetryEOF\b" TIMEOUT=1m ./test
+#
+#
+# Run code coverage
+# COVERDIR must either be a absolute path or a relative path to the etcd root
+# $ COVERDIR=coverage PASSES="build_cov cov" ./test
+set -e
 
 source ./build
 
@@ -15,6 +49,10 @@ USERPKG=${PKG:-}
 
 # Invoke ./tests/cover.test.bash for HTML output
 COVER=${COVER:-"-cover"}
+PMEM=${PMEM:-}
+if [ -z "${PMEM}" ]; then
+	PMEM=false
+fi
 
 # Hack: gofmt ./ will recursively check the .git directory. So use *.go for gofmt.
 IGNORE_PKGS="(vendor/|etcdserverpb|rafttest|gopath.proto|v3lockpb|v3electionpb)"
@@ -98,7 +136,9 @@ fi
 
 function unit_pass {
 	echo "Running unit tests..."
-	GO_TEST_FLAG="-tags='pmem'"
+	if [ "${PMEM}" ]; then
+		GO_TEST_FLAG="-tags='pmem'"
+	fi
 	if [ "${VERBOSE}" == "1" ]; then
 		GO_TEST_FLAG="-v"
 	fi
